### ISSUE TITLE
PYTHON CLASE 02  parte 2.3 y 2-4

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Cuarto-Semestre#10]
2.3 Tipo float como constructor y comienzo de exponencial

[Teclear aquí para VER el video 4](https://drive.google.com/file/d/1rCS8uqI5c4Vza5YGnKoRTQRBNU30-wGF/view?usp=drive_link)

2.4 Exponencial negativo y positivo

[Teclear aquí para VER el video 5](https://drive.google.com/file/d/1z9q5uL7L3MelHxh9CNaIqO9uZJEj3Xiu/view?usp=drive_link)

**Comment by CreatemyGithub19** [comment]
porfa Nico hace el merge

**Comment by CreatemyGithub19** [comment]
Tarea realizada
