### ISSUE TITLE
Node clase 07ç

### ISSUE THREAD

**Issue by Dany1970** [CodeSystem2022/Code-People-Cuarto-Semestre#115]
Clase 07 Herramientas de desarrollo y producción

Hoy vamos a avanzar en lo que son las herramientas que podemos usar en el desarrollo y en producción

7.1 Nodemon -> herramienta para el desarrollo

Instalación

[Teclear aquí para VER el video 1](https://drive.google.com/file/d/18ct4Zq3XqQlLKJXGg9isfIbCLXAX_USa/view?usp=drive_link)

[Documentación](https://github.com/remy/nodemon#nodemon)

7.2 Problemas con Window -> ejecución de nodemon

[Enlace](https://www.cdmon.com/es/blog/la-ejecucion-de-scripts-esta-deshabilitada-en-este-sistema-te-contamos-como-actuar)

[Teclear aquí para VER el video 2](https://drive.google.com/file/d/1MfbQLURym9zKnxvj6WDnCAN6DdIPLOm6/view?usp=drive_link)

7.3 PM2 -> herramienta para producción

Instalación

[Teclear aquí para VER el video 3](https://drive.google.com/file/d/13bw7gizXumCOOcJp_7iDBOZlbo4OsaV6/view?usp=drive_link)

7.4 Ejecución de PM2

Parte -> 1

[Teclear aquí para VER el video 4](https://drive.google.com/file/d/10oSxO5vbFfcRPeSQiT7gZBO4hC-2A7KF/view?usp=drive_link)

Parte -> 2

[Teclear aquí para VER el video 5](https://drive.google.com/file/d/1YoDrVbhSaBAPfNvmbLK58fmAmo1DLk7e/view?usp=drive_link)

**Comment by Matu8990** [comment]
![Image](https://github.com/CodeSystem2022/Code-People-Cuarto-Semestre/assets/102619951/0404d4bb-dc0c-42c1-921f-48441570b3f1)
![Image](https://github.com/CodeSystem2022/Code-People-Cuarto-Semestre/assets/102619951/26da80f2-80c3-4620-abbe-768c990b4f3c)
![Image](https://github.com/CodeSystem2022/Code-People-Cuarto-Semestre/assets/102619951/8d03de74-3fd9-4d93-8353-ce4015b3e93f)
