### ISSUE TITLE
JAVASCRIPT CLASE 02  " 2.1 y2.2"

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Cuarto-Semestre#12]
2.1 Código de botón de compra

[Teclear aquí para VER el video 1](https://drive.google.com/file/d/1XeMo8D93ink34UTWmLRI2NzN3c0JjIYE/view?usp=drive_link)

2.2 Código de carrito

[Teclear aquí para VER el video 2](https://drive.google.com/file/d/1pzD00qCXd_7nNPmi_hhzjduQMkvv2b-O/view?usp=drive_link)

**Comment by Matu8990** [comment]
HECHO
