### ISSUE TITLE
NODE CLASE 02 2.1 Viendo variables let y const , con ejecución en terminal 2.2 Terminamos con un hola mundo y añadimos buena información sobre Node

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Cuarto-Semestre#18]
2.1 Viendo variables let y const , con ejecución en terminal

[Teclear aquí para VER el video 1](https://drive.google.com/file/d/1zFKYRpC8vmWCxDF6EX38C9hhpJ2cPUYV/view?usp=drive_link)

2.2 Terminamos con un hola mundo y añadimos buena información sobre Node

[Teclear aquí para VER el video 2](https://drive.google.com/file/d/1Wk_Szw1RwI6HBtCVtBSoyvAsFYIEf5ul/view?usp=drive_link)

**Comment by Matu8990** [comment]
HECHO
