### ISSUE TITLE
Cuerpo y pie de página,clase 03

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Cuarto-Semestre#29]
3.1 Avanzamos en el Body

[Teclear aquí para VER el video 1](https://drive.google.com/file/d/1GJ6w7nMIczUQVZT5gaxzK3CP63XMl4Q2/view?usp=drive_link)

3.2 Ahora vamos al Footer

[Teclear aquí para VER el video 2](https://drive.google.com/file/d/1XoMctsXJNM7uNRo4Bh2CrDgdE05kxcJo/view?usp=drive_link)

**Comment by CreatemyGithub19** [comment]
aceptado!
