### ISSUE TITLE
Configurar cantidad de producto y agregar boton para sumar o restar.,clase 03

### ISSUE THREAD

**Issue by Rcalb** [CodeSystem2022/Code-People-Cuarto-Semestre#30]
3.3 Configuramos las cantidades de productos

[Teclear aquí para VER el video 3](https://drive.google.com/file/d/1OeIGld_KXEAFQ3hmpghjTsYwMx6Hqv0Z/view?usp=drive_link)

3.4 Botones de suma y resta de productos

[Teclear aquí para VER el video 4](https://drive.google.com/file/d/188hpNJIi5I_Id42QTTDEEY-4AeVJntf2/view?usp=drive_link)

**Comment by Dany1970** [comment]
Listo @Rcalb ya se puede hacer el merge, pero no me acuerdo cómo ponerte como revisor.

**Comment by Rcalb** [comment]
No me apareció el botón para hacer el merger, solo cerre el issue.
