### ISSUE TITLE
PYTHON-Clase 05 Profundizando en String 5.4-5.5

### ISSUE THREAD

**Issue by Marianela00** [CodeSystem2022/Code-People-Cuarto-Semestre#65]
5.4 Método join para colecciones a cadenas -> Parte 1 y 2

[Teclear aquí para VER el video 5](https://drive.google.com/file/d/1FRr5UhVgKHeXIjY9y315mA4JUrgdQO5V/view?usp=drive_link)

[Teclear aquí para VER el video 6](https://drive.google.com/file/d/1HDaUtasqLcvPPtDad3gcZigdta1kFdBJ/view?usp=drive_link)

5.5 Método split cadena a lista -> Parte 1 y 2

[Teclear aquí para VER el video 7](https://drive.google.com/file/d/1d2h9boGRWjW00q2PbUbD7QRDOyhxL1CC/view?usp=drive_link)

[Teclear aquí para VER el video 8](https://drive.google.com/file/d/1YrV6UClh7jUM7_uTsEMp7Vaob8qs7GBp/view?usp=drive_link)

**Comment by Matu8990** [comment]
Hecho
