### ISSUE TITLE
6.3 Uso del método format() -> utilizamos place holder

### ISSUE THREAD

**Issue by CreatemyGithub19** [CodeSystem2022/Code-People-Cuarto-Semestre#79]
6.3 Uso del método format() -> utilizamos place holder 

Parte -> 1

[Teclear aquí para VER el video 3](https://drive.google.com/file/d/1gqYTMrQ6SGoPhxD8jFsEkh03dW2m_01C/view?usp=drive_link)

Parte -> 2

[Teclear aquí para VER el video 4](https://drive.google.com/file/d/1tMVLx6OCkwaF_YQjh-8Z3O8LWxPSQ49w/view?usp=drive_link)

Parte -> 3

**Comment by Matu8990** [comment]
Hecho
