### ISSUE TITLE
Clase 04 Profundizamos la teoría en Node

### ISSUE THREAD

**Issue by CreatemyGithub19** [CodeSystem2022/Code-People-Cuarto-Semestre#84]
Vamos a profundizar un poco más la forma en que trabaja Node...

4.2 EventLoop -> bucle de elementos Parte 1 y 2

[Teclear aquí para VER el video 2](https://drive.google.com/file/d/1ESRgv_elaHGwUkZX4Ek5nEmaKQxYplqe/view?usp=drive_link)

[Teclear aquí para VER el video 3](https://drive.google.com/file/d/1pySaw145ciOWA1sOIc_duXRHKkM1fblm/view?usp=drive_link)

bucle de elementos Parte 3

[Teclear aquí para VER el video 3](https://drive.google.com/file/d/1pySaw145ciOWA1sOIc_duXRHKkM1fblm/view?usp=drive_link)

**Comment by Dany1970** [comment]
Nada para codear
